# Generated by Django 3.2.7 on 2021-09-15 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_escritorio', models.CharField(max_length=150, verbose_name='Local do Escritorio')),
                ('percentual_legislacao', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Percentual da Legislação')),
                ('capacidade_total', models.PositiveIntegerField(null=True, verbose_name='Capacidade Total')),
            ],
            options={
                'verbose_name_plural': 'Escritorios',
                'db_table': 'escritorio',
            },
        ),
        migrations.CreateModel(
            name='Sala_Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.PositiveIntegerField(unique=True, verbose_name='Número da Sala')),
                ('escritorio_reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendai.escritorio', verbose_name='Escritorio de Reunião')),
            ],
            options={
                'verbose_name_plural': 'Sala_Reuniões',
                'db_table': 'sala_reuniao',
            },
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cadeira', models.PositiveIntegerField(verbose_name='Numero Cadeira')),
                ('status_cadeira', models.BooleanField(default=True, verbose_name='Status Cadeira')),
                ('local_escritorio_cadeira', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendai.escritorio', verbose_name='Local Cadeira')),
            ],
            options={
                'verbose_name_plural': 'Cadeiras',
                'db_table': 'cadeira',
            },
        ),
        migrations.CreateModel(
            name='Agendamento_Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data e Hora do Inicio')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Data e Hora do Fim')),
                ('status_reuniao', models.BooleanField(default=True, verbose_name='Status Agendamento Reunião')),
                ('lugar_reuniao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendai.escritorio', verbose_name='Escritorio')),
                ('sala_reuniao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendai.sala_reuniao', verbose_name='Numero da Sala')),
            ],
            options={
                'verbose_name_plural': 'Agendamentos das Reuniões',
                'db_table': 'agendamento_reuniao',
            },
        ),
        migrations.CreateModel(
            name='Agendamento_Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('status_escritorio', models.BooleanField(default=True, verbose_name='Status Agendamento Escritorio')),
                ('lugar_cadeira', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendai.cadeira', verbose_name='Cadeira')),
                ('lugar_escritorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendai.escritorio', verbose_name='Escritorio')),
            ],
            options={
                'verbose_name_plural': 'Agendamentos dos Escritorios',
                'db_table': 'agendamento_escritorio',
            },
        ),
    ]
