# Generated by Django 3.2.7 on 2021-09-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala_reuniao',
            name='numero_sala',
            field=models.PositiveIntegerField(verbose_name='Número da Sala'),
        ),
    ]
